[package]
name = "scop42"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
ash = "0.37.3"
glam = "0.27.0"
winapi = { version = "0.3.9", features = ["winuser", "libloaderapi"] }
winit = "0.29.15"
