services:
  frontend:
    ports:
      - 5173:5173
    stdin_open: true
    tty: true
    volumes:
      - ./:/node/app:delegated
    build:
      target: starter
      context: ./
    dns:
      - 8.8.8.8